/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as dashboardTrashRouteImport } from './routes/(dashboard)/trash'
import { Route as dashboardSettingsRouteImport } from './routes/(dashboard)/settings'
import { Route as dashboardProjectsRouteImport } from './routes/(dashboard)/projects'
import { Route as dashboardNotesRouteImport } from './routes/(dashboard)/notes'
import { Route as dashboardFilesRouteImport } from './routes/(dashboard)/files'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardTrashRoute = dashboardTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardSettingsRoute = dashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardProjectsRoute = dashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardNotesRoute = dashboardNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardFilesRoute = dashboardFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof dashboardIndexRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/files': typeof dashboardFilesRoute
  '/notes': typeof dashboardNotesRoute
  '/projects': typeof dashboardProjectsRoute
  '/settings': typeof dashboardSettingsRoute
  '/trash': typeof dashboardTrashRoute
}
export interface FileRoutesByTo {
  '/': typeof dashboardIndexRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/files': typeof dashboardFilesRoute
  '/notes': typeof dashboardNotesRoute
  '/projects': typeof dashboardProjectsRoute
  '/settings': typeof dashboardSettingsRoute
  '/trash': typeof dashboardTrashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(dashboard)/files': typeof dashboardFilesRoute
  '/(dashboard)/notes': typeof dashboardNotesRoute
  '/(dashboard)/projects': typeof dashboardProjectsRoute
  '/(dashboard)/settings': typeof dashboardSettingsRoute
  '/(dashboard)/trash': typeof dashboardTrashRoute
  '/(dashboard)/': typeof dashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/files'
    | '/notes'
    | '/projects'
    | '/settings'
    | '/trash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/files'
    | '/notes'
    | '/projects'
    | '/settings'
    | '/trash'
  id:
    | '__root__'
    | '/(auth)'
    | '/(dashboard)'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(dashboard)/files'
    | '/(dashboard)/notes'
    | '/(dashboard)/projects'
    | '/(dashboard)/settings'
    | '/(dashboard)/trash'
    | '/(dashboard)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)': {
      id: '/(dashboard)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/trash': {
      id: '/(dashboard)/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof dashboardTrashRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/settings': {
      id: '/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof dashboardSettingsRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/projects': {
      id: '/(dashboard)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof dashboardProjectsRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/notes': {
      id: '/(dashboard)/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof dashboardNotesRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/files': {
      id: '/(dashboard)/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof dashboardFilesRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface dashboardRouteRouteChildren {
  dashboardFilesRoute: typeof dashboardFilesRoute
  dashboardNotesRoute: typeof dashboardNotesRoute
  dashboardProjectsRoute: typeof dashboardProjectsRoute
  dashboardSettingsRoute: typeof dashboardSettingsRoute
  dashboardTrashRoute: typeof dashboardTrashRoute
  dashboardIndexRoute: typeof dashboardIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardFilesRoute: dashboardFilesRoute,
  dashboardNotesRoute: dashboardNotesRoute,
  dashboardProjectsRoute: dashboardProjectsRoute,
  dashboardSettingsRoute: dashboardSettingsRoute,
  dashboardTrashRoute: dashboardTrashRoute,
  dashboardIndexRoute: dashboardIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
